In [1]:
!pip install numpy

In [2]:
import numpy as np

# 1.converting list into arraty and assing numpy array

In [18]:
lst=[1,2,3,4,5,6]
print(type(lst))
arr=np.array(lst)
print(type(arr))
arr=np.array(lst,ndmin=2)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3 4 5 6]]


# 2.arange function

In [26]:
arr=np.arange(0,24,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


# 3.Multidimensional Arrays

In [28]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 4. Size function

In [30]:
print(arr.size)
print(np.size(arr))
print(np.size(arr,0))#no.of rows
print(np.size(arr,1))#no. of colums

12
12
4
3


# 5.Shape Function and Dtype

In [33]:
print(np.shape(arr))
print(arr.dtype)

(4, 3)
int64


# 6.Ndim

In [35]:
print(arr.ndim)
#OR
print(np.ndim(arr))

2
2


# 7.Zeros and Ones fn

In [42]:
zeros=np.zeros((3,4),int)
print(zeros)
zeros1=np.zeros((3,4),float)
print(zeros1)
ones=np.ones((3,4),int)
print(ones)
ones1=np.ones((3,4),float)
print(ones1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 8.Eye fn

In [44]:
#to create identity matrix
I=np.eye(3,dtype=int)
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# 9.empty fn

In [50]:
arr=np.empty(shape=(3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 10. Random Fns

In [3]:
arr=np.random.rand(3,4)
arr

array([[0.81178196, 0.76035082, 0.34836244, 0.24124474],
       [0.119177  , 0.90452275, 0.1174752 , 0.86200091],
       [0.87426712, 0.59209938, 0.16794257, 0.35164679]])

In [6]:
arr=np.random.randint(1,10,10)
arr

array([7, 5, 8, 6, 6, 8, 4, 7, 1, 8])

In [9]:
arr=np.random.randn(10)
arr

array([ 0.27574338, -0.29673815,  0.70825427, -0.82544901,  0.81454328,
        1.62106931,  0.13839809,  1.77940923, -0.52416949, -0.7512025 ])

# 11.Reshape


In [42]:
arr=np.random.randint(1,10,(3,4))
arr

array([[7, 2, 5, 6],
       [8, 2, 7, 3],
       [7, 3, 7, 8]])

In [13]:
arr=arr.reshape(6,2)
arr

array([[2, 6],
       [7, 2],
       [7, 2],
       [2, 4],
       [3, 9],
       [6, 5]])

# 12.linspace and logspace

In [15]:
arr=np.linspace(1,10,7)
arr

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [19]:
arr=np.logspace(1,20,10,base=2)#works without base also
arr

array([2.00000000e+00, 8.64047791e+00, 3.73289293e+01, 1.61269894e+02,
       6.96724480e+02, 3.01001624e+03, 1.30039894e+04, 5.61803417e+04,
       2.42712501e+05, 1.04857600e+06])

# 13.flatten

In [77]:
arr=arr.flatten()#flatten the array used in reshape function
arr

array([9, 4, 9, 9, 1, 6, 4, 6, 8, 7, 1, 5])

# 14.copy

In [24]:
arr

array([5, 4, 3, 7, 7, 8, 4, 8, 9, 3, 4, 4])

In [25]:
arr1=np.copy(arr)
arr1

array([5, 4, 3, 7, 7, 8, 4, 8, 9, 3, 4, 4])

In [26]:
print(id(arr))
print(id(arr1)) #difference in the id of each array

4453274544
4463573296


# 15.Max ,Min ,Sum

In [33]:
arr1.max()

9

In [35]:
arr1.min()

3

In [36]:
arr1.sum()

66

In [43]:
arr

array([[7, 2, 5, 6],
       [8, 2, 7, 3],
       [7, 3, 7, 8]])

In [44]:
arr.max(axis=0)

array([8, 3, 7, 8])

In [45]:
arr.min(axis=1)

array([2, 2, 3])

In [46]:
print(arr.sum(axis=0))#column
print(arr.sum(axis=1))#row

[22  7 19 17]
[20 20 25]


# 16.seed

In [65]:
np.random.seed(3)
arr=np.random.randint(1,10,(3,4))
print(arr)

[[9 4 9 9]
 [1 6 4 6]
 [8 7 1 5]]


# 17.Sort

In [66]:
arr

array([[9, 4, 9, 9],
       [1, 6, 4, 6],
       [8, 7, 1, 5]])

In [67]:
np.sort(arr)#row sort

array([[4, 9, 9, 9],
       [1, 4, 6, 6],
       [1, 5, 7, 8]])

In [69]:
np.sort(arr,0)#Column sort

array([[1, 4, 1, 5],
       [8, 6, 4, 6],
       [9, 7, 9, 9]])

In [71]:
np.sort(arr,1,kind="mergsort")

array([[4, 9, 9, 9],
       [1, 4, 6, 6],
       [1, 5, 7, 8]])

# 15.percentile

In [79]:
arr.sort()

In [80]:
np.percentile(arr,100)

9.0

# 16.Statastics

# Mean

In [84]:
np.random.seed(3)
arr=np.random.randint(1,10,10)
arr

array([9, 4, 9, 9, 1, 6, 4, 6, 8, 7])

In [85]:
np.mean(arr)

6.3

# variance 

In [86]:
np.var(arr)

6.410000000000001

# Standard deviation

In [87]:
np.std(arr)

2.5317977802344327

# 17.filtering 

In [88]:
arr=np.random.randint(1,10,20)

In [89]:
arr

array([1, 5, 8, 9, 2, 7, 3, 3, 2, 4, 6, 9, 2, 9, 8, 9, 2, 1, 6, 5])

In [90]:
arr[arr>5]

array([8, 9, 7, 6, 9, 9, 8, 9, 6])

# 18.Transpose

In [94]:
np.random.seed(3)
arr=np.random.randint(1,10,(3,4))
print(arr)
print(arr.T)

[[9 4 9 9]
 [1 6 4 6]
 [8 7 1 5]]
[[9 1 8]
 [4 6 7]
 [9 4 1]
 [9 6 5]]


# 19.where Fn

In [95]:
arr=np.where(arr%2==0,"even",arr)
arr

array([['9', 'even', '9', '9'],
       ['1', 'even', 'even', 'even'],
       ['even', '7', '1', '5']], dtype='<U21')

# 20.merging arrays

In [96]:
np.concatenate((arr1,arr2),axis=0)
np.vstack
np.hstack

NameError: name 'arr2' is not defined

# 21.splitting arrays

In [103]:
np.vsplit(arr,3)

[array([['9', 'even', '9', '9']], dtype='<U21'),
 array([['1', 'even', 'even', 'even']], dtype='<U21'),
 array([['even', '7', '1', '5']], dtype='<U21')]

# Images into array

In [104]:
from matplotlib.image import imread

In [107]:
img=imread("fit_code.png")

In [109]:
img.shape

(500, 500, 4)

In [111]:
img.max()

1.0

In [112]:
img.min()

0.0